# Config for cbformat
#
# Formats fenced code blocks in markdown. This config needs to be in the
# home folder, as cbmft doesn't use the XDG_CONFIG_HOME approach to finding configs;
# it only traverses up the current directory
#
# See https://github.com/lukas-reineke/cbfmt
[languages]
go = ["gofmt"]
javascript = ["prettierd -"]
lua = ["stylua -s -"]
python = ["black --fast -"]
rust = ["rustfmt"]
shell = ["shfmt -"]
svelte = ["prettierd --parser=svelte -"]
typescript = ["prettierd -"]
