git:
  diffRenderers:
    - command: difft --color=always
      type: extDiff
gui:
  theme:
    inactiveBorderColor:
      - "#666666"
    selectedLineBgColor:
      - "#1e1e1e"
    defaultFgColor:
      - "#aaaaaa"
