---
version: 1.3.0
default_namespace: larrybotha
config_home_path: /Users/larrybotha/.config/hoard
trove_path: /Users/larrybotha/.config/hoard/trove.yml
query_prefix: "  >"
primary_color:
  - 242
  - 229
  - 188
secondary_color:
  - 181
  - 118
  - 20
tertiary_color:
  - 50
  - 48
  - 47
command_color:
  - 180
  - 118
  - 20
parameter_token: "#"
parameter_ending_token: "!"
read_from_current_directory: true
sync_server_url: "https://troveserver.herokuapp.com/"
api_token: ~
