require("plugins/neodev") -- must be run before lsp
require("plugins/cmp")
require("plugins/formatter")
require("plugins/gitsigns")
require("plugins/indent-blankline")
require("plugins/mason") -- must be before lsp
require("plugins/lsp")
require("plugins/lspfuzzy")
require("plugins/neogen")
require("plugins/null-ls")
require("plugins/nvim-dap")
require("plugins/nvim-web-devicons")
require("plugins/obsidian")
require("plugins/rust-tools")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/lualine")
require("plugins/trouble")
