---
# We can get a quick default mux layout using this file and running:
# $ tmuxinator start d
name: <%= Dir.pwd.split('/')[-1] %>

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim -c DoTheSession
        -
